### ISSUE TITLE
Play sound after session or breaks

### ISSUE THREAD

**Issue by jonnieey** [ayoisaiah/focus#6] opened 2022-06-17 09:54 UTC
Is it possible to play a sound after a session and after break (like a beep or notification sound) in addition to the system notification?

**Comment by ayoisaiah** [comment] 2022-06-18 10:46
@jonnieey It's possible to play ambient sounds, but I'll look into adding support for a beeping sound soon

**Comment by jonnieey** [comment] 2022-06-18 12:46
@ayoisaiah Like not during a session or a break, when a sesion or a break ends. For example, when we transition from a task session to a break session, play a beep on that transition to notify of change.

`--notification-sound beep` or `-ns beep`

**Comment by ayoisaiah** [comment] 2022-06-18 16:39
@jonnieey Yes I understand, thanks for the clarification. Will get it done soon :)

**Comment by jonnieey** [comment] 2022-06-20 06:56
Or maybe allow user to run custom commands for each transition or event. eg `--short-break-cmd = paplay beep.mp3`

**Comment by ayoisaiah** [comment] 2022-06-20 07:14
> Or maybe allow user to run custom commands for each transition or event. eg `--short-break-cmd = paplay beep.mp3`  

That makes a lot of sense actually. I'll provide a default and a way to override it 👍

**Comment by ayoisaiah** [comment] 2022-09-26 20:39
Closed via https://github.com/ayoisaiah/focus/commit/44098660e10998b56c3488787467afd07d8f6114

**Closed by ayoisaiah** 2022-09-26 20:39 UTC

**Comment by ayoisaiah** [comment] 2022-11-21 22:47
@jonnieey The default system notification sound should play after each session along with the notification. You can build from source to test it out.

Also, I've added a `--session-cmd` option for running arbitrary commands after a session.

**Comment by jonnieey** [comment] 2023-02-23 00:30
> @jonnieey The default system notification sound should play after each session along with the notification. You can build from source to test it out.
> 
> Also, I've added a `--session-cmd` option for running arbitrary commands after a session.

The cmd arg `--session-cmd` works but not from configuration `session_cmd`

**Comment by ayoisaiah** [comment] 2023-02-23 07:37
![Screenshot from 2023-02-23 08-35-29](https://user-images.githubusercontent.com/13372163/220844871-0e9010b2-6841-4c2b-97f6-b13ce4686fb5.png)

I'm not able to reproduce. Are you on v1.3.0?

**Comment by jonnieey** [comment] 2023-02-23 08:03
Updated and now it works, thanks
